In [1]:
MyFirstList = [3,45,56, 732]

In [2]:
MyFirstList

[3, 45, 56, 732]

In [3]:
type(MyFirstList)

list

In [11]:
l2 = ["hell", 24, True, 55.3]

In [12]:
l2

['hell', 24, True, 55.3]

In [13]:
type(l2)

list

In [14]:
l3 = ['how are you?', 55, MyFirstList]

In [15]:
l3

['how are you?', 55, [3, 45, 56, 732]]

In [16]:
range(15)

range(0, 15)

In [17]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [18]:
y = list(range(8))

In [19]:
y

[0, 1, 2, 3, 4, 5, 6, 7]

In [20]:
z = list(range(1,8))

In [21]:
z

[1, 2, 3, 4, 5, 6, 7]

In [22]:
z2 = list(range(100, 120))

In [23]:
z2

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119]

In [24]:
w = list(range(100, 120, 2))

In [25]:
w

[100, 102, 104, 106, 108, 110, 112, 114, 116, 118]

In [26]:
w = ['a', 'b', 'c', 'd', 'e']

In [27]:
w[0]

'a'

In [28]:
len(w)

5

In [29]:
w[-1]

'e'

In [30]:
w[-3]

'c'

In [31]:
w[2] = 63

In [32]:
w

['a', 'b', 63, 'd', 'e']

## Slicing

In [34]:
w[0:4:2]

['a', 63]

In [35]:
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [36]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [37]:
letters[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [38]:
letters[:6]

['A', 'B', 'C', 'D', 'E', 'F']

In [39]:
letters[2:]

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [40]:
letters[2:7]

['C', 'D', 'E', 'F', 'G']

In [41]:
letters[-8:7]

['C', 'D', 'E', 'F', 'G']

In [42]:
letters[-8:-3]

['C', 'D', 'E', 'F', 'G']

In [43]:
letters[2:9:2]

['C', 'E', 'G', 'I']

In [44]:
letters[::3]

['A', 'D', 'G', 'J']

In [47]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

## Tuples - Immutable List

In [48]:
t1 = (345, 674, 934)

In [49]:
t1

(345, 674, 934)

In [50]:
t1[1]

674

In [51]:
t1[1] = 45

TypeError: 'tuple' object does not support item assignment

## Functions

In [52]:
range(20, 31)

range(20, 31)

In [53]:
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [54]:
mylist1 = list(range(20,31))

In [55]:
mylist1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [56]:
print(mylist1)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [57]:
len(mylist1)

11

In [58]:
type(mylist1)

list

In [59]:
max(mylist1)

30

In [60]:
min(mylist1)

20

In [61]:
sum(mylist1)

275

## Numpy and Arrays

In [65]:
l = [23245, 27, 546, 215, -1234]

In [66]:
l

[23245, 27, 546, 215, -1234]

In [67]:
import numpy as np

In [68]:
np.array(l)

array([23245,    27,   546,   215, -1234])

In [71]:
a = np.array(l)

In [72]:
a

array([23245,    27,   546,   215, -1234])

In [73]:
b = np.array([12, 455, 63.3, True, 'a'])

In [74]:
b

array(['12', '455', '63.3', 'True', 'a'], dtype='<U32')

In [75]:
print(b)

['12' '455' '63.3' 'True' 'a']


In [76]:
l.pop()

-1234

In [77]:
l

[23245, 27, 546, 215]

In [78]:
a.mean()

4559.8

### Slicing Arrays

In [80]:
a

array([23245,    27,   546,   215, -1234])

In [81]:
a[2:]

array([  546,   215, -1234])

In [82]:
a[2:4]

array([546, 215])

In [83]:
b = a[2:4]

In [84]:
b[0]

546

In [85]:
b[:] = 111

In [86]:
a

array([23245,    27,   111,   111, -1234])

In [87]:
# When creating a slice of an array you are not creating a new array, just a different view of the array.

In [88]:
c = a.copy()

In [89]:
c[0] = 0

In [90]:
a

array([23245,    27,   111,   111, -1234])

In [91]:
c

array([    0,    27,   111,   111, -1234])

## Homework

In [92]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [96]:
#Profit
profit =list([])
for i in range(0, len(revenue)):
    profit.append(revenue[i] - expenses[i])
    
profit

[2522.67,
 1911.3900000000003,
 -3707.790000000001,
 -2914.3099999999995,
 -599.9200000000001,
 7265.24,
 8210.550000000001,
 3944.9700000000003,
 3328.3899999999994,
 -2238.6500000000015,
 659.5999999999985,
 11629.54]

In [99]:
#Taxes
tax = [round(i * 0.3, 2) for i in profit]
tax

[756.8,
 573.42,
 -1112.34,
 -874.29,
 -179.98,
 2179.57,
 2463.17,
 1183.49,
 998.52,
 -671.6,
 197.88,
 3488.86]

In [100]:
# Profit after taxes
profit_after_tax = list([])

for i in range(0, len(profit)):
    profit_after_tax.append(profit[i] - tax[i])
profit_after_tax

[1765.8700000000001,
 1337.9700000000003,
 -2595.4500000000007,
 -2040.0199999999995,
 -419.94000000000005,
 5085.67,
 5747.380000000001,
 2761.4800000000005,
 2329.8699999999994,
 -1567.0500000000015,
 461.71999999999855,
 8140.68]

In [103]:
#profit after tax divided by revenue as a percentage
profit_margin = list([])

for i in range(0, len(profit)):
    profit_margin.append(profit_after_tax[i]/revenue[i])
profit_margin

profit_margin = [round((i * 100),2) for i in profit_margin]
profit_margin

[12.12,
 17.59,
 -30.14,
 -22.23,
 -5.21,
 62.74,
 49.99,
 28.28,
 22.61,
 -10.9,
 4.31,
 52.75]

In [104]:
#Profit after tax mean
mean_pat = sum(profit_after_tax)/len(profit_after_tax)
mean_pat

1750.6816666666666

In [105]:
#good months
good_months = list([])

for i in range(0, len(profit)):
    good_months.append(profit_after_tax[i] > mean_pat)
good_months

[True, False, False, False, False, True, True, True, True, False, False, True]

In [106]:
#bad months
bad_months = list([])

for i in range(0, len(profit)):
    bad_months.append(profit_after_tax[i] < mean_pat)
bad_months

[False, True, True, True, True, False, False, False, False, True, True, False]

In [107]:
# best month
best_month = list([])

for i in range(0, len(profit)):
    best_month.append(profit_after_tax[i] == max(profit_after_tax))
best_month

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [108]:
# worst month
worst_month = list([])

for i in range(0, len(profit)):
    worst_month.append(profit_after_tax[i] == min(profit_after_tax))
worst_month

[False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [109]:
#Convert all calculations to units of 1000 dollars
revenue_1000 = [round(i/1000, 2) for i in revenue]
expenses_1000 = [round(i/1000, 2) for i in expenses]
profit_1000 = [round(i/1000, 2) for i in profit]
profit_after_tax_1000 = [round(i/1000, 2) for i in profit_after_tax]

revenue_1000 = [int(i) for i in revenue_1000]
expenses_1000 = [int(i) for i in expenses_1000]
profit_1000 = [int(i) for i in profit_1000]
profit_after_tax_1000 = [int(i) for i in profit_after_tax_1000]